[package]
name = "excuse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
ansi_term = "0.12"
serde = { version = "1.0.138", features = ["derive"] }
toml = "0.5.9"
